import './globals.css';

import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';

import { Toaster } from '@/components/ui/toaster';
import { LocaleContextProvider } from '@/context/locale.context';
import { PhoneContextProvider } from '@/context/phone.context';
import { UserContextProvider } from '@/context/user.context';

const inter = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Magiclink',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LocaleContextProvider>
          <PhoneContextProvider>
            <UserContextProvider>
              {children}
              <Toaster />
            </UserContextProvider>
          </PhoneContextProvider>
        </LocaleContextProvider>
      </body>
    </html>
  );
}
